# -*- coding: utf-8 -*-
"""Simulation Aetherium Animée

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13gaBcpWr6SqJzwEqgAf_UJ4dbhi9_VGX
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Simulation Aetherium (Gross-Pitaevskii-Poisson) en 2D avec Animation
Basé sur la formulation par champ de phase de R. Morin (2026).
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

# ==========================================
# Paramètres de la simulation
# ==========================================
N = 128             # Résolution de la grille (augmentée pour un plus beau rendu)
L = 2 * np.pi       # Taille du domaine
dx = L / N
x = np.linspace(0, L, N, endpoint=False)
y = np.linspace(0, L, N, endpoint=False)
X, Y = np.meshgrid(x, y, indexing='ij')

# Espace spectral pour les dérivées (FFT)
kx = np.fft.fftfreq(N, d=dx) * 2 * np.pi
ky = np.fft.fftfreq(N, d=dx) * 2 * np.pi
KX, KY = np.meshgrid(kx, ky, indexing='ij')
K2 = KX**2 + KY**2

# Paramètres physiques "Aetherium"
g = 2.0         # Non-linéarité (Pression locale répulsive)
alpha = 1.5     # Couplage de Poisson (Gravité/Attraction auto-cohérente)
dt = 0.005      # Pas de temps temporel
steps_per_frame = 5 # Nombre de calculs entre chaque image affichée

# ==========================================
# Conditions Initiales (Instabilité)
# ==========================================
rho0 = 1.0
# On place deux "gouttes" de surdensité qui vont interagir
bump1 = 0.8 * np.exp(-((X-L/3)**2 + (Y-L/2)**2)/0.3)
bump2 = 0.8 * np.exp(-((X-2*L/3)**2 + (Y-L/2)**2)/0.3)
rho_init = rho0 + bump1 + bump2

# Champ de phase créant une rotation (vortex)
theta_init = np.sin(X) * np.cos(Y) * 2.0

# Construction du champ complexe initial psi
psi = np.sqrt(rho_init) * np.exp(1j * theta_init)

# ==========================================
# Fonctions du Solveur Spectral
# ==========================================
def solve_poisson(rho, rho0, K2, alpha):
    """
    Résout le potentiel auto-cohérent V (équation de Poisson).
    """
    rho_diff_hat = np.fft.fftn(rho - rho0)
    V_hat = np.zeros_like(rho_diff_hat)
    mask = K2 != 0
    V_hat[mask] = -alpha * rho_diff_hat[mask] / K2[mask]
    return np.real(np.fft.ifftn(V_hat))

def split_step(psi, dt):
    """
    Intégrateur Split-Step Fourier (SSF).
    """
    # 1. Demi-étape cinétique
    psi_hat = np.fft.fftn(psi)
    psi_hat *= np.exp(-1j * (dt / 4.0) * K2)
    psi = np.fft.ifftn(psi_hat)

    # 2. Étape potentielle complète
    rho = np.abs(psi)**2
    V = solve_poisson(rho, rho0, K2, alpha)
    V_eff = V + g * rho
    psi *= np.exp(-1j * dt * V_eff)

    # 3. Demi-étape cinétique
    psi_hat = np.fft.fftn(psi)
    psi_hat *= np.exp(-1j * (dt / 4.0) * K2)
    psi = np.fft.ifftn(psi_hat)

    return psi

# ==========================================
# Configuration de l'Animation Matplotlib
# ==========================================
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))
fig.suptitle("Modèle Aetherium : Dynamique Schrödinger-Poisson", fontsize=14)

# Panneau de gauche : Densité
im_rho = ax1.imshow(np.abs(psi)**2, cmap='magma', origin='lower', extent=[0, L, 0, L], vmin=0, vmax=3.0)
ax1.set_title(r"Densité fluide $\rho = |\psi|^2$")
ax1.set_xlabel("x"); ax1.set_ylabel("y")
fig.colorbar(im_rho, ax=ax1, fraction=0.046, pad=0.04)

# Panneau de droite : Phase
im_theta = ax2.imshow(np.angle(psi), cmap='twilight', origin='lower', extent=[0, L, 0, L], vmin=-np.pi, vmax=np.pi)
ax2.set_title(r"Phase $\theta$ (Potentiel des vitesses)")
ax2.set_xlabel("x"); ax2.set_ylabel("y")
fig.colorbar(im_theta, ax=ax2, fraction=0.046, pad=0.04)

time_text = ax1.text(0.05, 0.95, '', transform=ax1.transAxes, color='white', weight='bold')

def update(frame):
    global psi

    # Exécuter plusieurs pas de temps par image d'animation pour accélérer la vidéo
    for _ in range(steps_per_frame):
        psi = split_step(psi, dt)

    # Mettre à jour les données des graphiques
    rho_current = np.abs(psi)**2
    theta_current = np.angle(psi)

    im_rho.set_array(rho_current)
    im_theta.set_array(theta_current)

    # Ajuster dynamiquement l'échelle de couleur si la densité augmente
    max_rho = np.max(rho_current)
    if max_rho > im_rho.get_clim()[1]:
        im_rho.set_clim(vmax=max_rho * 1.1)

    time_text.set_text(f'Tps = {frame * dt * steps_per_frame:.3f}')

    return im_rho, im_theta, time_text

# Création de l'animation
ani = animation.FuncAnimation(fig, update, frames=200, interval=40, blit=False)

print("Lancement de l'animation... Fermez la fenêtre pour arrêter.")
plt.tight_layout()

# --- Décommente la ligne ci-dessous pour sauvegarder en GIF (requiert Pillow) ---
# ani.save('aetherium_simulation.gif', writer='pillow', fps=24)

plt.show()