# -*- coding: utf-8 -*-
"""Simulateur Aetherium 3D GPU

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PZI6_hvMgr9PRgF5i1YmXhcZ0RfsUalb
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Moteur Aetherium 3D GPU (PyTorch)
---------------------------------
Simulation volumique (3D) du fluide supercritique Schrödinger-Poisson.
Preuve de concept d'un substrat de calcul continu pour l'AGI.
"""

import torch
import torch.fft
import numpy as np
import matplotlib.pyplot as plt

class AetheriumCore3D(torch.nn.Module):
    def __init__(self, N=64, L=2*np.pi, g=2.0, alpha=1.5, dt=0.005, device=None):
        super().__init__()

        # Détection automatique du GPU (CUDA ou Apple Metal MPS)
        if device is None:
            if torch.cuda.is_available():
                self.device = torch.device('cuda')
            elif torch.backends.mps.is_available():
                self.device = torch.device('mps')
            else:
                self.device = torch.device('cpu')
        else:
            self.device = torch.device(device)

        print(f"Initialisation de l'AetheriumCore 3D sur : {self.device}")

        self.N = N
        self.L = L
        self.g = g
        self.alpha = alpha
        self.dt = dt
        self.dx = L / N

        # 1. Création de la grille spatiale 3D (X, Y, Z)
        x = torch.linspace(0, L, N, device=self.device)[:-1]
        y = torch.linspace(0, L, N, device=self.device)[:-1]
        z = torch.linspace(0, L, N, device=self.device)[:-1]
        X, Y, Z = torch.meshgrid(x, y, z, indexing='ij')

        # 2. Nombres d'onde pour la FFT 3D
        kx = torch.fft.fftfreq(N, d=self.dx, device=self.device) * 2 * np.pi
        ky = torch.fft.fftfreq(N, d=self.dx, device=self.device) * 2 * np.pi
        kz = torch.fft.fftfreq(N, d=self.dx, device=self.device) * 2 * np.pi
        KX, KY, KZ = torch.meshgrid(kx, ky, kz, indexing='ij')

        # 3. Opérateur Laplacien 3D (K^2)
        self.K2 = KX**2 + KY**2 + KZ**2

        # Pré-calcul de l'opérateur d'évolution cinétique
        self.kinetic_op = torch.exp(-1j * (self.dt / 4.0) * self.K2)

    def solve_poisson(self, rho, rho0=1.0):
        """Résout l'équation de Poisson 3D sur GPU"""
        rho_diff = rho - rho0
        rho_diff_hat = torch.fft.fftn(rho_diff)

        V_hat = torch.zeros_like(rho_diff_hat)
        mask = self.K2 != 0
        V_hat[mask] = -self.alpha * rho_diff_hat[mask] / self.K2[mask]

        return torch.fft.ifftn(V_hat).real

    def forward(self, psi):
        """
        Passe forward : Exécute un pas de temps (Split-Step Fourier)
        Le code est identique à la 2D grâce aux tenseurs n-dimensionnels !
        """
        # Demi-étape Cinétique
        psi_hat = torch.fft.fftn(psi)
        psi_hat = psi_hat * self.kinetic_op
        psi = torch.fft.ifftn(psi_hat)

        # Étape Potentielle (Non-linéaire)
        rho = torch.abs(psi)**2
        V = self.solve_poisson(rho)
        V_eff = V + self.g * rho
        psi = psi * torch.exp(-1j * self.dt * V_eff)

        # Demi-étape Cinétique finale
        psi_hat = torch.fft.fftn(psi)
        psi_hat = psi_hat * self.kinetic_op
        psi = torch.fft.ifftn(psi_hat)

        return psi

# ==========================================
# Exécution de la simulation 3D
# ==========================================
if __name__ == "__main__":
    # Paramètres
    N_grid = 64 # Pour tester rapidement (monter à 128 ou 256 si GPU puissant)
    steps = 100

    aetherium3D = AetheriumCore3D(N=N_grid, g=2.0, alpha=1.5)

    # Création du volume d'espace-temps initial
    x = torch.linspace(0, aetherium3D.L, aetherium3D.N, device=aetherium3D.device)
    X, Y, Z = torch.meshgrid(x, x, x, indexing='ij')

    # État initial 3D : Deux bulles de densité proches (fusion/interaction)
    bump1 = torch.exp(-((X-aetherium3D.L/2.5)**2 + (Y-aetherium3D.L/2)**2 + (Z-aetherium3D.L/2)**2)/0.3)
    bump2 = torch.exp(-((X-aetherium3D.L/1.5)**2 + (Y-aetherium3D.L/2)**2 + (Z-aetherium3D.L/2)**2)/0.3)
    rho_init = 1.0 + 1.2 * (bump1 + bump2)

    # Phase 3D (Vorticité intriquée sur les 3 axes)
    theta_init = torch.sin(X*2) * torch.cos(Y*2) * torch.sin(Z)

    psi = torch.sqrt(rho_init) * torch.exp(1j * theta_init)

    print(f"Volume alloué : {N_grid}x{N_grid}x{N_grid} tenseurs complexes.")
    print(f"Calcul de {steps} pas de temps sur GPU...")

    with torch.no_grad():
        for i in range(steps):
            psi = aetherium3D(psi)

            # Sécurité
            if i % 20 == 0:
                max_rho = torch.max(torch.abs(psi)**2).item()
                print(f" Étape {i:03d} - Densité max : {max_rho:.3f}")

    print("Calcul terminé ! Stabilité 3D confirmée.")

    # ---------------------------------------------------------
    # Visualisation : Extraction de la coupe centrale (Plan XY au milieu de Z)
    # ---------------------------------------------------------
    # On ramène la densité volumique sur le CPU
    rho_volumique = (torch.abs(psi)**2).cpu().numpy()

    # Coupe au milieu de l'axe Z (indice N//2)
    coupe_z = N_grid // 2
    rho_slice = rho_volumique[:, :, coupe_z]

    plt.figure(figsize=(7, 6))
    plt.imshow(rho_slice, cmap='inferno', origin='lower')
    plt.title(f"Aetherium 3D : Coupe centrale (Z={coupe_z}) après {steps} itérations")
    plt.colorbar(label="Densité $\\rho$")
    plt.xlabel("X")
    plt.ylabel("Y")

    plt.savefig('aetherium_3d_gpu_slice.png', dpi=150)
    print("Résultat sauvegardé dans 'aetherium_3d_gpu_slice.png'")