# -*- coding: utf-8 -*-
"""Simulateur Aetherium GPU (PyTorch)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ufLfhWtMgUZt-iWroMps0KVKjET4NBNR
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Moteur Aetherium GPU (PyTorch) pour l'Intelligence Artificielle Fluide
----------------------------------------------------------------------
Ce script transforme le modèle de Gross-Pitaevskii-Poisson (GPP) en un
module d'IA accéléré par GPU. Il permet d'envisager l'Aetherium comme
un "Réservoir" pour le calcul neuromorphique (Reservoir Computing).
"""

import torch
import torch.fft
import numpy as np
import matplotlib.pyplot as plt

class AetheriumCore(torch.nn.Module):
    def __init__(self, N=128, L=2*np.pi, g=1.0, alpha=1.0, dt=0.005, device=None):
        super().__init__()

        # Détection automatique du GPU (CUDA ou Apple Metal MPS)
        if device is None:
            if torch.cuda.is_available():
                self.device = torch.device('cuda')
            elif torch.backends.mps.is_available():
                self.device = torch.device('mps')
            else:
                self.device = torch.device('cpu')
        else:
            self.device = torch.device(device)

        print(f"Initialisation de l'AetheriumCore sur : {self.device}")

        self.N = N
        self.L = L
        self.g = g
        self.alpha = alpha
        self.dt = dt
        self.dx = L / N

        # Création de la grille spatiale
        x = torch.linspace(0, L, N, device=self.device)[:-1]
        y = torch.linspace(0, L, N, device=self.device)[:-1]
        X, Y = torch.meshgrid(x, y, indexing='ij')

        # Nombres d'onde pour la FFT
        kx = torch.fft.fftfreq(N, d=self.dx, device=self.device) * 2 * np.pi
        ky = torch.fft.fftfreq(N, d=self.dx, device=self.device) * 2 * np.pi
        KX, KY = torch.meshgrid(kx, ky, indexing='ij')

        # Opérateur Laplacien (K^2)
        self.K2 = KX**2 + KY**2

        # Pré-calcul de l'opérateur d'évolution cinétique (demi-étape)
        # e^{-i * (dt/4) * K^2}
        self.kinetic_op = torch.exp(-1j * (self.dt / 4.0) * self.K2)

    def solve_poisson(self, rho, rho0=1.0):
        """Résout l'équation de Poisson sur GPU via FFT"""
        rho_diff = rho - rho0
        rho_diff_hat = torch.fft.fftn(rho_diff)

        V_hat = torch.zeros_like(rho_diff_hat)
        mask = self.K2 != 0
        V_hat[mask] = -self.alpha * rho_diff_hat[mask] / self.K2[mask]

        return torch.fft.ifftn(V_hat).real

    def forward(self, psi):
        """
        Passe 'forward' standard en IA.
        Exécute un pas de temps (Split-Step Fourier)
        """
        # 1. Demi-étape Cinétique
        psi_hat = torch.fft.fftn(psi)
        psi_hat = psi_hat * self.kinetic_op
        psi = torch.fft.ifftn(psi_hat)

        # 2. Étape Potentielle (Non-linéaire)
        rho = torch.abs(psi)**2
        V = self.solve_poisson(rho)
        V_eff = V + self.g * rho
        psi = psi * torch.exp(-1j * self.dt * V_eff)

        # 3. Demi-étape Cinétique finale
        psi_hat = torch.fft.fftn(psi)
        psi_hat = psi_hat * self.kinetic_op
        psi = torch.fft.ifftn(psi_hat)

        return psi

# ==========================================
# Exemple d'utilisation (Preuve de concept IA)
# ==========================================
if __name__ == "__main__":
    # 1. Initialisation du coeur fluide (Réservoir)
    aetherium = AetheriumCore(N=256, g=2.0, alpha=1.5)

    # 2. Création de l'état initial (Input)
    X, Y = torch.meshgrid(
        torch.linspace(0, aetherium.L, aetherium.N, device=aetherium.device),
        torch.linspace(0, aetherium.L, aetherium.N, device=aetherium.device),
        indexing='ij'
    )

    # État initial complexe (tenseurs PyTorch)
    rho_init = 1.0 + 1.0 * torch.exp(-((X-aetherium.L/2)**2 + (Y-aetherium.L/2)**2)/0.2)
    theta_init = torch.sin(X*3) * torch.cos(Y*3)
    psi = torch.sqrt(rho_init) * torch.exp(1j * theta_init)

    # 3. Simulation (Calcul fluide)
    steps = 100
    print(f"Calcul de {steps} pas de temps sur GPU...")

    # Pas besoin de calcul de gradient pour l'instant (mode inférence)
    with torch.no_grad():
        for _ in range(steps):
            psi = aetherium(psi) # Appel de la fonction forward

    print("Calcul terminé ! (Absence de blow-up vérifiée)")

    # 4. Rapatriement sur CPU pour l'affichage
    rho_final = (torch.abs(psi)**2).cpu().numpy()

    plt.figure(figsize=(6,5))
    plt.imshow(rho_final, cmap='magma', origin='lower')
    plt.title("Aetherium GPU : Densité après 100 itérations")
    plt.colorbar()
    plt.savefig('aetherium_gpu_result.png')
    print("Résultat sauvegardé dans 'aetherium_gpu_result.png'")