# -*- coding: utf-8 -*-
"""Simulation Aetherium avec Citations

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G9f4kioc85jbpV9YNi7mmQxBMyyb_U9G
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Simulation Aetherium (Gross-Pitaevskii-Poisson) en 2D avec Animation
Code annoté avec les références au papier de R. Morin (2026).
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

# Paramètres de la grille (2D pour une exécution rapide sur un simple CPU)
N = 64
L = 2 * np.pi
dx = L / N
x = np.linspace(0, L, N, endpoint=False)
y = np.linspace(0, L, N, endpoint=False)
X, Y = np.meshgrid(x, y, indexing='ij')

# Nombres d'onde pour les dérivées spectrales (FFT)
kx = np.fft.fftfreq(N, d=dx) * 2 * np.pi
ky = np.fft.fftfreq(N, d=dx) * 2 * np.pi
KX, KY = np.meshgrid(kx, ky, indexing='ij')
K2 = KX**2 + KY**2 # Opérateur Laplacien en espace spectral

# Paramètres physiques du papier
g = 1.0       # Paramètre de non-linéarité contrôlant la pression locale
alpha = 1.0   # Intensité du couplage de Poisson
dt = 0.005    # Pas de temps
steps_per_frame = 5 # Nombre de calculs entre chaque image affichée

# État initial : construction du champ de phase complexe
rho0 = 1.0 # Densité de base
rho_init = rho0 + 0.5 * np.exp(-((X-L/2)**2 + (Y-L/2)**2)/0.5) # Forte concentration de masse
theta_init = np.sin(X) * np.cos(Y) # Gradient de phase (crée un cisaillement/vorticité)
psi = np.sqrt(rho_init) * np.exp(1j * theta_init) # Équation (1) : psi = sqrt(rho) * e^(i*theta)

def solve_poisson(rho, rho0, K2, alpha):
    """ Résout l'équation (3) : Laplace(V) = alpha * (rho - rho0) dans l'espace spectral """
    rho_diff_hat = np.fft.fftn(rho - rho0)
    V_hat = np.zeros_like(rho_diff_hat)
    mask = K2 != 0 # Évite la division par zéro sur la composante continue
    V_hat[mask] = -alpha * rho_diff_hat[mask] / K2[mask]
    return np.real(np.fft.ifftn(V_hat))

def split_step(psi, dt):
    """ Intégrateur Split-Step Fourier (SSF) tel que décrit dans l'équation (8) """

    # 1. Demi-étape Cinétique (Espace de Fourier)
    psi_hat = np.fft.fftn(psi)
    psi_hat *= np.exp(-1j * (dt / 4.0) * K2)
    psi = np.fft.ifftn(psi_hat)

    # 2. Étape Potentielle complète (Espace physique)
    rho = np.abs(psi)**2
    V = solve_poisson(rho, rho0, K2, alpha)
    V_eff = V + g * rho # Couplage potentiel V et auto-interaction non-linéaire g|psi|^2
    psi *= np.exp(-1j * dt * V_eff)

    # 3. Demi-étape Cinétique finale (Espace de Fourier)
    psi_hat = np.fft.fftn(psi)
    psi_hat *= np.exp(-1j * (dt / 4.0) * K2)
    psi = np.fft.ifftn(psi_hat)

    return psi

# ==========================================
# Configuration de l'Animation Matplotlib
# ==========================================
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))
fig.suptitle("Modèle Aetherium : Dynamique Schrödinger-Poisson", fontsize=14)

# Panneau de gauche : Densité
im_rho = ax1.imshow(np.abs(psi)**2, cmap='magma', origin='lower', extent=[0, L, 0, L], vmin=0, vmax=3.0)
ax1.set_title(r"Densité fluide $\rho = |\psi|^2$")
ax1.set_xlabel("x"); ax1.set_ylabel("y")
fig.colorbar(im_rho, ax=ax1, fraction=0.046, pad=0.04)

# Panneau de droite : Phase
im_theta = ax2.imshow(np.angle(psi), cmap='twilight', origin='lower', extent=[0, L, 0, L], vmin=-np.pi, vmax=np.pi)
ax2.set_title(r"Phase $\theta$ (Potentiel des vitesses)")
ax2.set_xlabel("x"); ax2.set_ylabel("y")
fig.colorbar(im_theta, ax=ax2, fraction=0.046, pad=0.04)

time_text = ax1.text(0.05, 0.95, '', transform=ax1.transAxes, color='white', weight='bold')

def update(frame):
    global psi

    # Évolution de la physique (plusieurs pas par frame)
    for _ in range(steps_per_frame):
        psi = split_step(psi, dt)
        if np.any(np.isnan(psi)):
            print(f"Instabilité numérique détectée à l'étape {frame * steps_per_frame} !")
            return im_rho, im_theta, time_text

    # Mise à jour de l'affichage
    rho_current = np.abs(psi)**2
    theta_current = np.angle(psi)

    im_rho.set_array(rho_current)
    im_theta.set_array(theta_current)

    # Ajustement dynamique de l'échelle si la densité augmente
    max_rho = np.max(rho_current)
    if max_rho > im_rho.get_clim()[1]:
        im_rho.set_clim(vmax=max_rho * 1.1)

    time_text.set_text(f'Tps = {frame * dt * steps_per_frame:.3f} | Max ρ = {max_rho:.2f}')

    return im_rho, im_theta, time_text

# Création et lancement de l'animation
ani = animation.FuncAnimation(fig, update, frames=200, interval=40, blit=False)

print("Lancement de la simulation animée...")
plt.tight_layout()
plt.show()